VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "hNFe4_Doc_det_prod_comb"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public cProdANP As String
Public descANP As String
Public pGLP As Double
Public pMist As Double
Public CODIF As String
Public qTemp As Double
Public UFComb As String
Public CIDE As New hNFe4_Doc_det_prod_comb_CID
Public encerrante As New hNFe4_Doc_det_prod_comb_Enc

