VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "hNFe4_ConsSitNFe"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public tpAmb As Long
Public cStat As Long
Public xMotivo As String
Public cUF As String
Public dhRecbto As String
Public chNFe As String
Public nProt As String
Public digVal As String
Public cMsg As Long
Public xMsg As String

